'''
reference: https://www.dogsofthedow.com/largest-companies-by-market-cap.htm
returns dictionaries of company list with its stock maeket name
'''

# Declare a dictionary with company full name as key
companies = {
	'Apple': 'AAPL',
	'Microsoft': 'MSFT',
	'Alphabet': 'GOOGL',
	'Amazon': 'AMZN',
	'Facebook': 'FB',
	'Tesla': 'TSLA',
	'Berkshire Hathaway': 'BRK.A',
	'Taiwan Semiconductor': 'TSM',
	'Alibaba': 'BABA',
	'Visa': 'V',
	'NVIDIA': 'NVDA',
	'JPMorgan Chase': 'JPM',
	'Johnson & Johnson': 'JNJ',
	'Walmart': 'WMT',
	'UnitedHealth': 'UNH',
	'Mastercard': 'MA',
	'Home Depot': 'HD',
	'Bank of America': 'BAC',
	'Procter & Gamble': 'PG',
	'ASML': 'ASML',
	'PayPal': 'PYPL',
	'Disney': 'DIS',
	'Adobe': 'ADBE',
	'Nike': 'NKE',
	'Pfizer': 'PFE',
	'Comcast': 'CMCSA',
	'Eli Lilly': 'LLY',
	'Oracle': 'ORCL',
	'Toyota': 'TM',
	'Exxon Mobil': 'XOM',
	'Coca-Cola': 'KO',
	'Cisco': 'CSCO',
	'Verizon': 'VZ',
	'Netflix': 'NFLX',
	'Salesforce': 'CRM',
	'Danaher': 'DHR',
	'Intel': 'INTC',
	'Abbott Labs': 'ABT',
	'Pepsi': 'PEP',
	'Thermo Fisher Scientific': 'TMO',
	'Novartis': 'NVS',
	'Wells Fargo': 'WFC',
	'Accenture': 'ACN',
	'AbbVie': 'ABBV',
	'AT&T': 'T',
	'Broadcom': 'AVGO',
	'Chevron': 'CVX',
	'Costco': 'COST',
	'Merck': 'MRK',
	'Shopify': 'SHOP'}


# Declare a dictionary with stock market symbol as key
companies_stock_market = {
	'AAPL': 'Apple',
	'MSFT': 'Microsoft',
	'GOOGL': 'Alphabet',
	'AMZN':  'Amazon',
	'FB': 'Facebook',
	'TSLA': 'Tesla',
	'BRK.A': 'Berkshire Hathaway',
	'TSM': 'Taiwan Semiconductor',
	'BABA': 'Alibaba',
	'V': 'Visa',
	'NVDA': 'NVIDIA',
	'JPM': 'JPMorgan Chase',
	'JNJ': 'Johnson & Johnson',
	'WMT': 'Walmart',
	'UNH': 'UnitedHealth',
	'MA': 'Mastercard',
	'HD': 'Home Depot',
	'BAC': 'Bank of America',
	'PG': 'Procter & Gamble',
	'ASML': 'ASML',
	'PYPL': 'PayPal',
	'DIS': 'Disney',
	'ADBE': 'Adobe',
	'NKE': 'Nike',
	'PFE': 'Pfizer',
	'CMCSA': 'Comcast',
	'LLY': 'Eli Lilly',
	'ORCL': 'Oracle',
	'TM': 'Toyota',
	'XOM': 'Exxon Mobil',
	'KO': 'Coca-Cola',
	'CSCO': 'Cisco',
	'VZ': 'Verizon',
	'NFLX': 'Netflix',
	'CRM': 'Salesforce',
	'DHR': 'Danaher',
	'INTC': 'Intel',
	'ABT': 'Abbott Labs',
	'PEP': 'Pepsi',
	'TMO': 'Thermo Fisher Scientific',
	'NVS': 'Novartis',
	'WFC': 'Wells Fargo',
	'ACN': 'Accenture',
	'ABBV': 'AbbVie',
	'T': 'AT&T',
	'AVGO': 'Broadcom',
	'CVX': 'Chevron',
	'COST': 'Costco',
	'MRK': 'Merck',
	'SHOP': 'Shopify'}